### ISSUE TITLE
Berichtsjahr anlegen

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#199]
Filter Berichtsjahr 2019 anlegen und automatisch setzen ab Feb 2019.
In Berichtsjahr 2018 abgeschlossen Fälle herausfiltern.

**Comment by adedden** [comment]
Die Filterung nach Berichtsjahr (die auch für die Statistikexport benutzt wird) scheint noch nicht richtig zu funktionieren.
Es gibt zurzeit die folgende Problemfälle, Matrikelnummer
944461
957675
962527

bei denen über StudIP der Abschluss der Promotion zum Januar 2019 eingetragen wurde. Diese Fälle werden (vielleicht dadurch) nicht mehr bei der Auswahl 'Berichtsjahr 2018' angezeigt und auch nicht im Statistikexport. Diese Fälle müssten jedoch bei der Meldung für 2018 eigentlich noch als nicht abgeschlossen gemeldet werden.

**Comment by adedden** [comment]
@asudau : du hast Recht, ZBW hat immer gesagt dass es keine Versionierung geben sollte, aber wir bemerken jetzt dass es technisch nicht funktioniert ohne so eine Versionierung. 

Deswegen sehe ich die Notwendigkeit, dass es die Vorgehensweise anpasst wird und die folgende Lösung einzubaut wird (kannst du das machen oder macht Till das?):
- Berichtsjahr YYYY: wenn 
Beginn der Promotion (EF13) < 1.12.YYYY und 
{ Ende der Promotion (EF14) ist NULL ODER ( Ende der Promotion (EF14) <= 1.12.YYYY und Ende der Promotion (EF14) > 1.12.(YYYY-1) ) }, dann gleich 1, sonnst 0
In Wörter: Parameter "Berichtsjahr YYYY" ist gleich 1, wenn die Promotion am Stichtag 1 Dezember YYYY bereits angefangen hat und es noch keine Abschluss erreicht wurde, oder wenn ein zwischen dem aktuellen und letzten Stichtag einen Abschluss erreicht wurde.

**Comment by adedden** [comment]
- Diese Parameter gerne für die Jahren 2018 bis 2022 anlegen.
- Das Filter auf der Übersichtseite entsprechend anpassen
- Die Erstellung der Statistikexports entsprechend anpassen

**Comment by tgloeggl** [comment]
Berichtsjahr dynamisch wählbar: 88444ea63c92c86e822282227ba7b1842672a903

**Comment by tgloeggl** [comment]
An folgender Stelle sind Query-Parameter zu sehen, die für die Filterung genutzt werden:
https://github.com/virtUOS/Promovierendenverwaltung/commit/88444ea63c92c86e822282227ba7b1842672a903#diff-73bc63f3af90bd27f75b09f084be9bffR8

**Comment by adedden** [comment]
Hi Till, sieht gut aus, Auswahl scheint im Export auch richtig zu greifen. 

Eine Bitte hätte ich noch: kannst du auch alle Fälle, die im art_reg_prom die Werte "Abbruch der Promotion" oder "Abschluss der Promotion (bestanden oder endgültig nicht bestanden"  stehen habe (entspricht (5 oder 6 in EF12)) , aber keine vollständige Daten zum Ende der Promotion haben (promotionsende_jahr und/oder promotionsende_monat sind leer), auch mitnehmen in der Berichtsjahrfilterung? 

Hintergrund für den Wunsch: ich möchte diese Fälle gerne aufführen, damit sie nicht verloren gehen/nicht aufgemerkt werden und deswegen nicht bereinigt werden.

**Comment by adedden** [comment]
Hi Till, kannst du das Filter 2019 so schnell wie möglich auf Stud.IP produktiv setzen?

**Comment by dschwass** [comment]
erledigt, administrator kann Berichtsjahr selbst anlegen
