### ISSUE TITLE
Fehlende Auswahlmöglichkeit für Graduiertenkollegs

### ISSUE THREAD

**Issue by kaschnie** [virtUOS/Promovierendenverwaltung#203]
Wir müssen dasGraduiertenkolleg "Die Produktion von Migration" mit als Auswahlfeld anbieten unter dem Feld "Teilnahme an einem strukurierten Promotionsprogramm". Hierbei handelt es sich um ein Graduiertenkolleg, das bis letztes Jahr im Oktober ging und somit noch für das Berichtsjahr 2018 relevant ist.

Könntet ihr das bitte noch kurzfristig mit in die Auswahlmöglichkeiten mit aufnehmen?

**Comment by kaschnie** [comment]
@asudau würdest du noch das Graduiertenkolleg in die Stammtabelle aufnehmen? Dann könnte die Bearbeiterin aus Fachbereich 8 die Promovierenden einpflegen.

**Comment by asudau** [comment]
ist erledigt

**Comment by kaschnie** [comment]
Dankeee!!
