### ISSUE TITLE
Promotionsfach importieren/anpassen

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#205]
- Schlüsseltabelle aus HIO: course_of_study und subject
- Promotionsfächer, sind Fächer aus "subject", die in course_of_study vorkommen mit degree_lid 100273 oder 100274 und die gültig sind (siehe Spalten "valid from", "valid to")
- lid wird benutzt für die Kopplung zum Promovierendentool

**Comment by adedden** [comment]
ist abgeschlossen

**Comment by sonschul** [comment]
Für Reportingzwecke benötigen wir die in Stud.IP hinterlegte Auswahlliste der Promotionsfächer. 
Ist es möglich diese als View im db-user campus zur Verfügung zu stellen?

**Comment by adedden** [comment]
hallo Elmar, gerne möchte ich die Filterung nach Abschlüsse ändern und zwar:

- degree.astat_bund = "06", "07", "91" und "92" und degree.hiskey_id = 1
