### ISSUE TITLE
Anpassungen im "Statistikexport"

### ISSUE THREAD

**Issue by kaschnie** [virtUOS/Promovierendenverwaltung#208]
-	In EF2 (Berichtsjahr) wird aktuelles Kalenderjahr 2019 ausgegeben – auf Berichtsjahr 2018 ändern
-	In EF22 (Jahr der Ersteinschreibung – nur vierstellig) tauchen aber auch Angaben wie 2001/2002 auf (s.u. MTKNR= 935151) --> müsste nur das erste Jahr 2001 ausgewiesen werden

Beispiel: MTKNR=935151
"Fachbereich 4: Physik";Orban XXX;XXX;XX.XX.XXXX;935151;05300000;03;**2019**;0530;000304;1;03;04;1982;Ioan;154;;01;767;3;03;2008;;;1;0;1;1;9990;154;2;**2001/2002**;1;9990;154;796;128;02;2008;8;2008;39;99;;;;;;;XXX@uos.de

**Comment by asudau** [comment]
Huhu, das mit dem Brichtsjahr ist kein Problem.  
Die Geschichte bei der Ersteinschreibung ist schon schwieriger, da man im Plugin so eine Jahreszahl gar nicht angeben könnte, da hier eine vierstellige Zahl erwartet wird, handelt es sich offenbar um 'unsaubere' Daten aus HIS. Ich weiß nicht so richtig was mach da machen kann/soll.. Ich könnte das natürich einfach abschneiden und nur die erste Zahl ausgeben..

**Comment by kaschnie** [comment]
Super! 
Du kannst gerne einfach die ersten 4 Zeichen ausgeben und den Rest abschneiden.

**Comment by kaschnie** [comment]
@asudau könntest du die Probleme noch korrigieren? Wir müssen am Donnerstag die Statisik liefern..

**Comment by asudau** [comment]
ist erledigt!

**Comment by asudau** [comment]
ach moment muss das plugin noch updaten

**Comment by asudau** [comment]
hmm das mach ich jetzt lieber nicht selbst da es bereits weitere Änderungen gab stimme ich das lieber vorher mit till ab, die geschichte mit dem jahr der ersteinschreibung funkioniert aber auch so schon.. falls das mit dem update bis donnerstag nicht mehr klappt kann man das berichtsjahr vemrutlihc notfalls auch noch von hand in der exportdatei austauschen.

**Comment by kaschnie** [comment]
@asudau das wäre super, wenn du mir Bescheid geben könntest, wenn ihr darüber gesprochen habt und feststeht, ob das mit dem Update klappt oder nicht :-)

**Comment by hdalingh** [comment]
Die obigen beiden Punkte sind jetzt entsprechend korrigiert, so dass der Export diesbezüglich nun passen sollte.
