### ISSUE TITLE
Korrektur/Erweiterungen "vollständiger Export"

### ISSUE THREAD

**Issue by kaschnie** [virtUOS/Promovierendenverwaltung#209]
-	Paginiernummer (EF4) muss 6-stellig ausgewiesen werden und in fortlaufender Nummerierung 
        (im Moment immer =1); im Statistikexport bereits korrekt
-	Alle Spalten, die aus HISinOne kommen müssten entsprechend in den Spaltenbenennungen  
        gekennzeichnet werden --> z. B. Staatsangehörigkeit_HIS, hochschule_erst_HIS usw.
-	EF22 nach vier Zeichen abschneiden (2000/2001) und bei „Jahr“ aus HISinOne ebenfalls
-	Spaltenbezeichnung „01 Fachbereich“ ändern in „01_Fachbereich“ und je nachdem, ob aus HISinOne,
        dann zusätzlich „_HIS"

Notwendge Erweiterungen:
Zusätzliche Spalten mit Langtexten/beschreibendem Text zu den ID-Spalten einfügen (wie in dem Export "Export der aktuellen Einträge").

**Comment by adedden** [comment]
Hallo Kathrin,

Entschuldigung für die späte Antwort. Also, ich brauche zuerst deine Punkte weiter zu klären, befor ich hieraus Tickets erstellen kann. Gerne möchte ich vorschlagen, dass du mir in der Zukunft eine Email schreibst, damit ich wir die Fragen klären können und ich danach die Tickets für die Entwickler erstellen kann. Das Ticketsystem möchte ich dann nur für das Verwaltung von Tickets für die Entwickler benutzen. Also, ich kläre diese Punkte mit der per Email.
