### ISSUE TITLE
(0) Importieren der Immatrikulation-daten: alle Promovierende selektieren

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#210]
Zuerst alle Immatrikulierten einschränken nach Promovierenden durch folgende Filterung:
- Nur alle Studierenden ausgeben, die einen Promotionsstudiengang studieren. Dies sind Studiengänge mit einem Abschluss Promotion.

Promotionsstudiengänge sind wie folgt zu finden:
- Studiengang: course_of_study, Abschluss der Studiengang ist zu finden in der Tabelle "degree" und wird aus course_of_study verlinkt via degree_lid
- Abschluss ist gleich Promotion, wenn astat_bund = "06"

Für Zuordnung von Personen zur Studiengänge, siehe Ticket #212

**Comment by hdalingh** [comment]
Hier sollten wir uns vielleicht auf die aktuell eingeschriebenen Fälle beschränken. Beim Student-Datensatz gibt es die Felder term_year (entspricht dem Jahr, z.B. 2018) und term_type_id (entspricht dem Semestertyp, 1= SoSe und 2= WiSe, aktuell 2) über die man z.B. die Einschränkung vornehmen könnte. Ansonsten gibt es noch beim Einschreibsatz (degree_program_progress) die Spalte period_id, wo dann über das Matching mit der Period-Tabelle auch auf period.term_year und period.term_type_id eine Filterung erfolgen könnte.

**Comment by adedden** [comment]
Hallo ihr beide,

Nein beschränken auf nur eingeschriebene Promovierenden reicht  nicht aus, da HIO das führendr System ist für alle Promovierenden die mal in HIO eingeschrieben waren. Bitte überlegt euch was ein sinnvoller Anzahl Semester ist um rückwirkend mitzunehmen.

**Comment by hdalingh** [comment]
Wir brauchen doch erstmal nur die Daten von aktuell eingeschriebenen Promovierenden-Studierenden aus HISinOne und nicht die vergangenen Einschreibsätze von allen Studierenden der letzten drei oder vier Semester, die potentiell zu Promovierenden werden könnten. 
Um ehemalige Studierende zu ermitteln, die vielleicht jetzt ohne Einschreibung bei uns promovieren, könnte man ja vielleicht separat eine Suchabfrage stellen, die solche Fälle dann aus den Personendaten ermitteln kann oder?

**Comment by adedden** [comment]
Hi Heike, brauchen wir doch, weil jemand aktiv promovieren kann, aber jetzt im Moment nicht eingeschrieben ist, aber es mal war. Auch für diese Fälle ist HIO das führende System, also sollen es rückwirkend Semester mitgenommen werden. Beschließt gerne wie viele Semester sinnvoll ist und gebe Elmar Bescheid dass er dieses Ticket umsetzen kann.

**Comment by dschwass** [comment]
Umsetzung mit dpp.finished wird verglichen mit heute vor fünf Jahren
