### ISSUE TITLE
(1) Importieren der Immatrikulation-Daten: Daten zur Person

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#211]
Nach #210

Folgende Daten zur Person sind zu importieren:
- Geschlecht
- Geburtsdatum
- Nachname
- Vorname
- E-Mail
- Staatsangehörigkeit
- Weitere Staatsangehörigkeit

Personendaten der Studierenden suchen, durch:
- Spalte Student.person linken mit Person.id
- Aus Person.id folgende Informationen holen:

- [ ] Geslecht = person.k_gender_id
- [ ] Geburtsdatum = person.birthdate
- [ ] Nachname = person.surname
- [ ] Vorname = person.firstname
- [ ] E-Mail = ?? (noch definieren TO DO Anne)

Staatangehörigkeit der Person suchen durch:
- Spalte personinfo.person_id linken mit Person.id

- Aus Person.id folgende Informationen holen:
- [ ] Staatsangehörigkeit = personinfo.country_lid
- [ ] Weitere Staatsangehörigkeit = personinfo.second_nationality_country_lid

**Comment by hdalingh** [comment]
Die in HISinOne hinterlegten E-Mails findet man über person_id in der Tabelle address mit dem zusätzlichen Filter address.addresstype='EMail' und der Einschränkung auf address.k_addresstag_id=7 für Login-EMail-Adresse oder  address.k_addresstag_id=8 für RZ-E-Mail.

**Comment by adedden** [comment]
Es soll auf adress.k_adresstag_id=8 eingeschränkt werden, also auf RZ-Emailadresse
