### ISSUE TITLE
(2) Importieren der Immatrikulation-Daten: Daten zur Einschreibung

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#212]
Zuerst der Studienverlauf der Person suchen:
- degree_program ist gelinkt zur Person über degree_program.person_id = person.id (es können mehrere degreeprograms pro Person gefunden werden)
- Studienverlauf ist dann dazu matchen: degree_program_progress, linken mit degree_program über degree_program_progress.degree_program_id= degree_program.id

- offene Frage: wie viele Perioden zurückliegend mitnehmen? (nochmal mit Heike und Elmar klären)

- [ ] Promotionsfach
- der aktuelle Promotionsfach (der Promotionsstudiengang, Definition siehe #210 ) ist der Fach, worin der Promovierende zuletzt (siehe startdate und enddate der Studienverlaufssatz) eingeschrieben war (@hdalingh : ist die Definition richtig, oder soll sie eingeschränkt werden zum aktuellen Semester? keine Semester in der Zukunft mitnehmen?)
- Studiengang gehörend zum Studienverlaufssatz ist zu finden in der Spalte course_of_study_id, Fach ist dann wieder in der Tabelle course_of_study im subject_lid zu finden
- Promotionsfach = subject_lid
- [ ] Matrikelnummer = student.registrationnumber

- [ ] Immatrikulation 
- Wenn degree_program_progress.finished für das die letzte/aktuellste Studiengangssatz kleiner gleich heute ist, dann ist Immatrikulation = 0, sonnst ist Immatrikulation = 1 (@hdalingh diese Definition überprüfen bitte!)

**Comment by hdalingh** [comment]
Da wir doch im Stud.IP-Plugin keine Historie vorhalten wollen, sollte nur der aktuelle Einschreibsatz berücksichtigt werden, oder wurde diesbezüglich doch eine andere Vereinbarung getroffen? Die aktuelle Einschreibung kann man entweder je Semester über student.term_year (=2018) und student.term_type_id (=2) (z.B. fürs WiSe 2018/19) ermitteln oder über das Feld period_id beim Einschreibsatz (degree_program_progress). 
Bei Feld Immatrikulation (1=Ja, 0=nein) würde ich alle Fälle mit 1 kennzeichnen, die zum aktuellen Semester in einem Promotionsstudiengang eingeschrieben sind.

**Comment by adedden** [comment]
Da HIO nicht nur das führende System für dir ImmaDaten sondern auch für andere Daten wie Daten zur Person , HZB und Ersteinschreibung ist diese Einschränkung nicht erwünscht

**Comment by adedden** [comment]
Wenn degree_program_progress.finished <= 5 Jahre her, dann berücksichtigen, sonnst raus damit :)
