### ISSUE TITLE
(3) Importieren der Immatrikulation-Daten: Daten zur Ersteinschreibung

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#213]
Es gibt zwei unterschiedliche Fälle: entweder Studierenden waren oder waren nicht an der Uni Osnabrück ersteingeschrieben. Im Fall, dass sie nicht an der UOS ersteingeschrieben waren:

Finde das Erststudium durch:
- Match Tabelle study_before durch study_before.person_id=person.id
- Aus der Tabelle study_before:

- [ ] Hochschule = university_lid
- [ ] Bei einer Hochschule ausserhalb Deutschlands, der Staat der Hochschule:   
- wenn university_lid =  2, dann = country_lid, sonnst country_lid =  48          
- [ ] Semester = first_term_type_id
- [ ] Jahr = first_term_year

@hdalingh Definitionen überprüfen, siehe Anhang, Doku HIS zur Tabelle "study_before"

**Comment by adedden** [comment]
![doku his study_before](https://user-images.githubusercontent.com/42414093/51996710-980a4080-24b5-11e9-86b2-9465ea0aa695.PNG)

**Comment by hdalingh** [comment]
Für den zweiten Fall "Studierender war Ersteinschreiber an der Uni OS" müssen die Angaben zur Ersteinschreibung aus dem Studienverlauf (degree_program_progress) abgelesen werden. Hierzu kann man die Datensätze auf den degree_program_progress-Datensatz filtern bei dem das Feld  degree_program_progress.k_studystatus_id=1 ist, d.h. (1= Ersteinschreiber, andere Werte sind 2= Neueinschreiber, 3= Rückmelder usw.).  Das entsprechende Semester kann dann über das Feld degree_program_progress.period_id ermittelt werden, wo das Jahr über period.term_year und das Semester über period.term_type_id abgefragt werden kann.

**Comment by adedden** [comment]
Hier nochmal die HIS-Wiki Seite mit Info zur Datenbankdokumentation der Ersteinschreibung:
[DB-Dokumentation Externe Studienangaben_Früheres Studium-HISinOne – HisWiki.pdf](https://github.com/virtUOS/Promovierendenverwaltung/files/3196955/DB-Dokumentation.Externe.Studienangaben_Fruheres.Studium-HISinOne.HisWiki.pdf)

**Comment by adedden** [comment]
@tgloeggl : könntest du nochmal überprüfen ob deine Abfrage jetzt richtig die DB-Struktur der HIS matcht?

**Comment by tgloeggl** [comment]
Das sollte jetzt passen.
