### ISSUE TITLE
(4) Importieren der Immatrikulation-Daten: Daten zur Hochschulzugangsberechtigung 

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#214]
Man gelingt zu den HZB Daten durch 2 Schritten:
- Match person.id zu examplan.person_id
- Match entrance_qualification.examplan_id to examplan.id

- [ ] Jahr = year(examplan.date_of_work)
- [ ] Art der HZB = entrance_qualification_type_id
- [ ] Kreis (bei Erwerb in Deutschland): ?? @hdalingh: weißt du wo dies herkommt?
- [ ] Staat (bei Erwerb im Ausland): ?? @hdalingh: weißt du wo dies herkommt?

**Comment by hdalingh** [comment]
Die Tabelle examplan kann man noch filtern auf nur die Sätze mit unit_id=1 (Leistung = HZB).

Der HZB-Kreis wird über die Tabelle examimport ermittelt und zwar über die Verknüpfung examimport.examplan_id=examplan.id und über das Feld examimport.district_lid. Das Feld examimport.district_lid muss dann über die Tabelle district.lid aufgeschlüsselt werden.

Das HZB-Land wird ebenfalls über die Tabelle examimport ermittelt und zwar auch über die Verknüpfung examimport.examplan_id=examplan.id und über das Feld examimport.country_lid. Das Feld examimport.country_lid muss dann über die Tabelle country.lid entsprechend aufgeschlüsselt werden.
