### ISSUE TITLE
Editierbarkeit der Felder aufheben nach Import der Immatrikulationsdaten aus HIO

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#215]
Sobald eine Person in HIO eingeschrieben wurde und es Immatrikulations-Daten in Stud.IP importiert wurden, sollen die folgende Felder nicht mehr in Stud.IP editierbar sein (sollen ausgegraut werden),da HIO dann das führende System geworden ist:

**Daten zur Person**
* Geschlecht
* Geburtsdatum
* Nachname
* Vorname
* E-Mail
* Staatsangehörigkeit
* Weitere Staatsangehörigkeit

**Daten zur Einschreibung**
* Promotionsfach
* Matrikelnummer
* Immatrikulation

**Daten zur Ersteinschreibung**
* Hochschule 
* Staat der Hochschule
* Semester
* Jahr

**Daten zur Hochschulzugangsberechtigung**
* Jahr
* Art der HZB
* Kreis (bei Erwerb in Deutschland)
* Staat (bei Erwerb im Ausland)

**Comment by tgloeggl** [comment]
Fiexed in https://github.com/virtUOS/Promovierendenverwaltung/commit/e72e3c3e6ba65850c4021b267b99102c91f77d09
