### ISSUE TITLE
Ende der Promotion Jahr kann nicht eingegeben werden

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#221]
Wenn z.B. eine Promotion erfolgreich beendet wurde, kann der Monat ausgewählt werden. Im Feld Jahr kann aber keine Eingabe erfolgen (Browser Firefox).

**Comment by tgloeggl** [comment]
Tritt das in der aktuellen Version im Testsystem immer noch auf?
Bei welchem Nutzer?

**Comment by dschwass** [comment]
ist gelöst. Das Jahr kann erfasst und werden.
