### ISSUE TITLE
Pflichtfeld Staat bei HS-Art Ausland setzen

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#227]
bei Daten zur Ersteinschreibung, Staat, wenn Hochschulart Ausland gewählt wurde, wird Staat kein Pflichtfeld, erst nach speichern (übernehmen) wird bei erneutem Aufruf das Feld Staat als Pflicht gekennzeichnet

**Comment by tgloeggl** [comment]
Soll das Feld lediglich als Pflichtfeld markiert werden oder soll auch sichergestellt werden, dass es tatsächlich ausgefüllt ist?

**Comment by KatharinaKroeger** [comment]
Was passiert, wenn sichergestellt wird, dass es tatsächlich ausgefüllt ist? Dann können die Bearbeiter den Datensatz wahrscheinlich nicht speichern, wenn es leer bleibt und es erscheint eine Fehlermeldung, oder?
Falls dies der Fall ist, dann am Besten erst mal nur als Pflichtfeld setzen, weil dies ein Feld ist, was schlecht nacherfasst ist. Bei ganz neu angelegten Doktoranden ist diese Info natürlich da, aber die Fehlermeldung würde ja dann wahrscheinlich auch kommen, sobald ein bestehender Datensatz bearbeitet wird und das Feld ungefüllt ist?

**Comment by tgloeggl** [comment]
Das Feld muss nicht zwangsweise ausgefüllt sein, es wird aber als auszufüllen korrekt markiert. Dies schlägt sich dementsprechend auch in der Prozentangabe nieder.
(Besprochen mit Dörthe)
