### ISSUE TITLE
nach Übernahme springt Berichtsauswahl auf 2019

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#228]
Ausgangslage: es ist Berichtsjahr "Alle Einträge" ausgewählt, ein Fall wird bearbeitet, nach Übernahme springt das Berichtsjahr auf 2019 um (der Fall erscheint dann nicht mehr)
Soll das so sein?

**Comment by tgloeggl** [comment]
fixed in b2aa937b1a4c2a965f8738ea9a538cc07d5b76a2
