### ISSUE TITLE
HZB-Arten - was wird angezeigt

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#229]
Daten zur Hochschulzugangsberechtigung, Art der HZB, können hier die Einträge zu Master und Bachelor ausgenommen werden
Woher kommen die Daten? aus der entrance_qualification_type oder aus einer anderen Quelle?
Wenn aus HISinOne werden dann die Gültigkeiten ausgewertet?

**Comment by KatharinaKroeger** [comment]
Ich habe im Schlüsselkatalog mal nachgeguckt und es gibt dort keine Einträge vom Master und Bachelor als HZB. Ich halte es auch nach wie vor nicht für HZB-Ausprägungen, weil diese nur den Hochschulzugang regeln, für einen Bachelor oder Master muss der Hochschulzugang aber ja bereits erfolgt sein.

**Comment by dschwass** [comment]
in der Auslieferung der HIS auf den Wikiseiten sind die Schlüssel auch nicht gelistet. Allerdings findet sich dort ein Hinweis zu den 80 Schlüsseln das diese nur für interne Zwecke verwendet werden. 
ich würde diese dann aus der Schlüsseltabelle entrancequalification_type entfernen. Die Tabelle muss dann neu in STUD.IP geladen werden.

**Comment by tgloeggl** [comment]
Muss ich da dann noch was tun oder erledigt sich das automatisch, wenn das Feld hzb_art aus entrance_qualification.entrance_qualification_type_id aktualisiert wird?

**Comment by tgloeggl** [comment]
Es passieren automatische stündliche Updates, hzb_art ist mit dabei.
