### ISSUE TITLE
Auswahl von Abschluss/Fach bei Daten zur Promotion einschränken

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#230]
Daten zur Promotion berechtigenden Abschlussprüfung: bei der Auswahl unter Studienfach und Abschluss werden alle Einträge aus degree und subject angezeigt, dabei kommt es zu Doppelungen und Unklarheiten;
1. Idee: wenn Hochschule = UOS dann nur interne Fächer (subject/degree.hiskey=1), wenn <> UOS dann nur externe Fächer subject/degree.hiskey=2) 
2. Idee: nur externe Fächer
Klärung mit ZBW (hier am Issue)

**Comment by KatharinaKroeger** [comment]
Wir tendieren eigentlich eher dazu, es so zu lassen, wie es ist. Die Bearbeiter scheint es nicht zu stören, dass es ein paar doppelte Fächer gibt, bzw. der Großteil wird es vermutlich nicht gemerkt haben. Da ja sowohl die internen als auch die externen Fächer alle auf die gleiche richtige Astat gehen, gibt es in der Statistik ja auch keine Probleme. 
Eine Umsetzung der 1. Idee wäre ja Aufwand, der unserer Meinung nach erspart bleiben kann. Eine Umsetzung der 2. Idee würde jedoch interne Fachbezeichnungen rauslöschen, die von den externen Abweichen, wo die Bearbeiter dann u. U. nicht wissen, welchem Fach sie es zuordnen können.
Wir könnten also gut damit leben, wenn es so bleibt, wie es ist.

**Comment by KatharinaKroeger** [comment]
ach, kannst du zukünftig die Sachen mit assignen und nicht Sonja, bitte? Danke

**Comment by tgloeggl** [comment]
Ich schließe dieses Ticket dann. Wenn in der Richtung doch noch was gemacht werden soll, einfach wieder öffnen!
