### ISSUE TITLE
kein update der HZB

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#233]
Fall 935102 
in HISinOne wurde die HZB von Gymnasium nach BerufsOSch./Fachak(aHR) geändert
die Änderung wurde nicht übernommen
(hisinone-tst - studip-tst)

**Comment by tgloeggl** [comment]
Ist behoben. (siehe: https://develop.studip.de/trac/changeset/54506 )
Ursache war, dass Studierende, die noch gar keinen Eintrag in degree_program_progress.finished hattetn, übersprungen wurden.
