### ISSUE TITLE
neue Sicht "noch zu bearbeiten" für immatrikulierte Fälle aus HISinOne

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#236]
durch Übernahme von immatrikulierten Fällen fehlen Daten wie Promobeginn,
über Promobeginn wird die zugehörigkeit zu Berichtsjahr geregelt,
daher die neue Sicht "noch zu bearbeiten" in der die Sachbearbeiter alle Fälle für ihre Fächer sehen, die noch mit Daten zu ergänzen sind

ist bereits umgesetzt: Bitte um Feedback

**Comment by KatharinaKroeger** [comment]
Die Sicht ist eine gute Idee, aber ich sehe sie noch nicht, sie ist jetzt auf dem Testsystem, oder? Magst du mir den Link einmal reinstellen oder per Mail schicken, ich war da immer noch nicht drauf und bin mir auch nicht sicher, ob ich schon berechtigt bin.

**Comment by dschwass** [comment]
Hallo Katharina,

 

hier der Link ins Testsystem. Dein Account sollte funktionieren.

https://studip-test.serv.uni-osnabrueck.de/ 

 

Gruß

Dörthe 

 

____________________________________________________________



Zentrum für Digitale Lehre, 

Campus-Management und Hochschuldidaktik

der Universität Osnabrück (virtUOS)

Bereich Campusmanagement

 

Heger-Tor-Wall 12

Gebäude 42

D-49069 Osnabrück 

Raum: 42/E06

Telefon: +49 (0) 541 969-6507

E-Mail:   dschwass@uni-osnabrueck.de <mailto:dschwass@uni-osnabrueck.de> 

URL:         <http://www.virtuos.uni-osnabrueck.de/> http://www.virtuos.uni-osnabrueck.de

Fax:        +49 (0) 541 969-16507

 

Von: kathkroe [mailto:notifications@github.com] 
Gesendet: Mittwoch, 6. November 2019 09:25
An: virtUOS/Promovierendenverwaltung <Promovierendenverwaltung@noreply.github.com>
Cc: dschwass <dschwass@uos.de>; Author <author@noreply.github.com>
Betreff: Re: [virtUOS/Promovierendenverwaltung] neue Sicht "noch zu bearbeiten" für immatrikulierte Fälle aus HISinOne (#236)

 

Die Sicht ist eine gute Idee, aber ich sehe sie noch nicht, sie ist jetzt auf dem Testsystem, oder? Magst du mir den Link einmal reinstellen oder per Mail schicken, ich war da immer noch nicht drauf und bin mir auch nicht sicher, ob ich schon berechtigt bin.

**Comment by dschwass** [comment]
bitte umbenennen in "neu Immatrikulierte"
