### ISSUE TITLE
HZB-Staat (Statistikfeld EF20) bei deutscher HZB mit Null in Statistik ausgeben

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#239]
durch den Import von HISinOne wird in das Feld "Staat" Deutschland übernommen, 
in dem Export für die Statistik soll aus dem Eintrag Deutschland ein Null-Wert werden in der Spalte "EF20", da eigentlich nur Angaben zu ausländischen HZB hier angegeben werden sollen

Evtl. überlegen, dass die Bezeichnung des Feldes "Staat (bei Erwerb im Ausland)" umbenannt werden soll?

**Comment by KatharinaKroeger** [comment]
Ja, das ist eine bessere Bezeichnung, die Statistik nennt es ja ähnlich "Bei Ersteinschreibung an einer Hochschule außerhalb Deutschlands der Staat der Hochschule". Ob Erwerb im Ausland oder außerhalb Deutschlands läuft ja auf das gleiche raus.
