### ISSUE TITLE
Feld "immatrikuliert" nur in einem def. Zeitraum aktualisieren

### ISSUE THREAD

**Issue by dschwass** [virtUOS/Promovierendenverwaltung#242]
Stichtag der Statistik 01.12., Nacharbeiten und Lieferung bis zum Februar;
daher muss gewährleistet sein, dass der Status "immatrikuliert" auch in der Zeit bis zur endgültigen Lieferung dem Stand vom 01.12. entspricht
daher soll das Feld nur in der Zeit vom 01.04. bis 1.12. (inkl.) aktualsiert werden.
in der Zeit vom 2.12. bis 31.03. soll zwar die Datensynchronisation vorgenommen werden, aber dieses Feld nicht aktualisiert werden

@tgloeggl Elmar setzt diese Anforderung um

**Comment by dschwass** [comment]
Till: Elmar hat die Sache noch nicht umgesetzt aber im Code die Stelle markiert. Kannst du das übernehmen?
Wir wollen demnächst die Daten nochmal synchronisieren und dann sollte das Feld nicht überschrieben werden in Stud.IP.

**Comment by tgloeggl** [comment]
Erledigt, siehe: https://develop.studip.de/trac/changeset/55735/
