### ISSUE TITLE
Immatrikulation (ef015) und Matrikelnummer automatisch erzeugen aus Import

### ISSUE THREAD

**Issue by adedden** [virtUOS/Promovierendenverwaltung#71]
Wenn Promovierende in STU Export verfügbar ist, sein/ihr Matrikelnummer importieren und Immatrikulation (ef015) auf 1 setzen. Wenn es nicht gefunden wird, auf 0 setzen. Beide Werten sollen in Phase 2 nicht mehr von Anwender bearbeitbar sein in der "Eintrag editieren"-Maske, nur lesbar.

**Comment by adedden** [comment]
Siehe #66

**Comment by hdalingh** [comment]
Hier möchte ich bedenken, dass nur weil ein Promovierender eine Matrikelnummer besitzt, es nicht unbedingt gleichzeitig heißt, das er immatrikuliert ist während seiner Promotion. Es kann auch nur eine Matrikelnummer von einer früheren Einschreibung im Bachelor oder im Master sein.

**Comment by asudau** [comment]
siehe #212

**Comment by adedden** [comment]
Auch in diesem Fall ist HIO das führende System für die Daten zur Person
